apiVersion: apps/v1
kind: Deployment
metadata:
  name: develeap-deployment
  labels:
    app: develeap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: develeap
  template:
    metadata:
      labels:
        app: develeap
    spec:
      containers:
        - name: develeap-container
          image: 069301198269.dkr.ecr.eu-north-1.amazonaws.com/develeapimg:latest
          ports:
            - containerPort: 80
